services:
  - type: web
    name: mcm-nomad-backend
    env: image
    image:
      url: ghcr.io/kmj830/nomad:latest
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mcm-nomad-db
          property: connectionString

databases:
  - name: mcm-nomad-db
    plan: free
    region: singapore
    databaseName: nomaddb
