services:
  - type: web
    name: mcm-nomad-backend
    env: java
    plan: free
    region: singapore
    buildCommand: ./gradlew bootJar
    startCommand: java -jar -Dspring.profiles.active=prod build/libs/nomad-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mcm-nomad-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mcm-nomad-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mcm-nomad-db
          property: password


databases:
  - name: mcm-nomad-db
    plan: free
    region: singapore
    databaseName: nomaddb

