server:
  port: ${PORT:8080}


spring:
  application:
    name: nomad
  profiles:
    active: dev

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha



---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:nomaddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nomaddb}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  tomcat:
    threads:
      max: 30
      min-spare: 5
    max-connections: 200


